spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paascloud_zipkin?characterEncoding=utf8&useSSL=false
    schema: classpath:/mysql.sql
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: '{cipher}AIB38bYLkVZMv91Czc7VNQkLtL8tXI1s7W0Nff8JKE2EKVeCh/YWdYjn6Ew3OGZMuEeaFxcwI8nIjhvz+I1KuliP/9yD+smAdyLSDDSnOlgZsu7H+OPtNyq0YTK6WdjscJsXa9wRJ2SpWYyU9q3eONDqqu58xaDq+2zCuo3LpKQTgMjhlEXbGO5zAZTRKkGM6F7EGq6L/gx/HTJwabUT8mTCNeIKy7nL8M5gy1yk33Ti1A=='
      username: '{cipher}AIB3N1xW3v9YWAsCn03c7P9qMsnZq5ZNcyGiWQeBexqDkMIcl9kPp2sT4bFUp4yAwErmw9KdbEeVrfmSz8O8xrdeZLwyEAJGWrx6qJ5C+fFGQvt6tZWX9KCNGaBRpW3/CF+fDJ2jhQjCJdJoHP8z3IqeSSJb5OGYi8JPKg4mApADqg7r8KH5WiCjZQVOgDIi0bhzkI32RP0N2d235TBvqFXZ'
      password: '{cipher}AIA7zqIpChvzcaKe8FCD1jWIrxD1cbI8BdPl+3RdGpfdOtuTUjhFYzh8vpKzPln55E17Z/FT6TA/vHuDwoiJTHhKWM7kaY5dR5UDX06KAZxuxOQbcs4UzxK38GZLpAo4LffM8iWssNHtB2IqoJydYFtJWb7Mex/mw+txmfwbe4oxQr45SLWIubV+IwAHd1vFybbKqucP+nZHS5HuSUNuZ19f'
      queue: zipkin
  storage:
    type: mysql

security:
  oauth2:
    client:
      clientId: paascloud-client-zipkin
      clientSecret: paascloudClientSecret
      access-token-uri: http://localhost:7979/uac/oauth/token
      user-authorization-uri: http://localhost:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://localhost:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:8000/oauth/token_key

paascloud:
  oauth2:
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
